import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { BreakpointIndicator } from '@/ram/components/util/BreakpointIndicator'
import { ThemeSwitch } from '../components/util/ui/ThemeSwitch'
import './globals.css'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
			<body className={inter.className}>
				<Providers>
					<ThemeSwitch />
					<BreakpointIndicator />
					{children}
				</Providers>
			</body>
		</html>
	)
}
